name: 'bin_dara'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["https://github.com/bin-dara/omni_dbt_integration/tree/main/models"]
seed-paths: ["seeds"]

models:
  +materialized: view
